# Generated by Django 3.0.5 on 2025-01-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('op1', models.TextField(default='')),
                ('op2', models.TextField(default='')),
                ('op3', models.TextField(default='')),
                ('answer', models.TextField(default='')),
            ],
        ),
    ]
