# Generated by Django 3.0.5 on 2025-01-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='op4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='op1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='op2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='op3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
